# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'YoongYoong' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YoongYoong
  # Async
    pod 'RxSwift', '5.1.1'
    pod 'RxCocoa', '5.1.1'
    pod 'RxDataSources', '~> 4.0'
  # UI
    pod 'SnapKit', '~> 5.0.0'
    pod 'IQKeyboardManagerSwift'
  # Code
    pod 'Then'
  # Map SDK
    pod 'NMapsMap','3.10.0'
  # Network
    pod 'Moya/RxSwift', '~> 14.0'

  target 'YoongYoongTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YoongYoongUITests' do
    # Pods for testing
  end

end
